module.exports = {
  apps: [
    {
      name: "claude-relay",
      script: "./start-relay.sh",
      cwd: "/home/edouard/claude-telegram-relay",
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 3000,
      kill_timeout: 12000,
      listen_timeout: 10000,
      shutdown_with_message: true,
      error_file: "/home/edouard/.claude-relay/logs/relay-error.log",
      out_file: "/home/edouard/.claude-relay/logs/relay-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claude-dashboard",
      script: "bun",
      args: "run dashboard/server.ts",
      cwd: "/home/edouard/claude-telegram-relay",
      autorestart: true,
      max_restarts: 10,
      min_uptime: "5s",
      restart_delay: 3000,
      error_file: "/home/edouard/.claude-relay/logs/dashboard-error.log",
      out_file: "/home/edouard/.claude-relay/logs/dashboard-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      env: {
        DASHBOARD_PORT: "3456",
      },
    },
    {
      name: "claude-heartbeat",
      script: "bun",
      args: "run src/heartbeat.ts",
      cwd: "/home/edouard/claude-telegram-relay",
      autorestart: false,
      cron_restart: "*/10 * * * *",
      error_file: "/home/edouard/.claude-relay/logs/heartbeat-error.log",
      out_file: "/home/edouard/.claude-relay/logs/heartbeat-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "claude-system-alerts",
      script: "./scripts/system-alerts.sh",
      cwd: "/home/edouard/claude-telegram-relay",
      autorestart: false,
      cron_restart: "*/15 * * * *",
      error_file: "/home/edouard/.claude-relay/logs/system-alerts-error.log",
      out_file: "/home/edouard/.claude-relay/logs/system-alerts-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
