-- Supabase Schema for Claude Telegram Relay
--
-- This file is kept for reference. The authoritative schema is in:
--   db/schema.sql
--
-- To set up your database:
-- 1. Go to your Supabase project's SQL Editor
-- 2. Copy and paste the contents of db/schema.sql
-- 3. Run the query
--
-- The schema includes:
-- - messages (conversation history with embeddings)
-- - memory (facts, goals, preferences with embeddings)
-- - logs (observability)
-- - tasks (backlog & sprint management)
-- - prds (product requirements documents)
-- - Helper functions: get_recent_messages, get_active_goals, get_facts,
--   get_sprint_summary, match_messages, match_memory
-- - Row Level Security on all tables
-- - Semantic search via vector embeddings
