/**
 * @module agent-schemas
 * @description Typed JSON output schemas per agent role, parsing, structured chain context.
 */

/**
 * Structured Agent Message Schemas — S22-01/02
 *
 * Defines typed JSON output schemas for each BMad agent role.
 * Replaces raw text concatenation with structured message passing
 * between agents in the orchestration pipeline.
 *
 * Each agent produces a typed output that downstream agents can parse
 * and extract exactly what they need.
 */

import type { AgentRole } from "./orchestrator.ts";

// ── Per-Role Output Schemas ──────────────────────────────────

export interface AnalystOutput {
  role: "analyst";
  analysis: string;
  risks: Array<{
    severity: "high" | "medium" | "low";
    description: string;
  }>;
  recommendations: string[];
  dependencies: string[];
  feasibility: "high" | "medium" | "low";
}

export interface PmOutput {
  role: "pm";
  subtasks: Array<{
    title: string;
    description: string;
    priority: number;
    acceptance_criteria: string;
    dependencies?: string[];
  }>;
  priorities: string[];
  risks: string[];
}

export interface ArchitectOutput {
  role: "architect";
  design: string;
  components: Array<{
    name: string;
    responsibility: string;
    interactions: string[];
  }>;
  files_impacted: string[];
  patterns: string[];
  technical_risks: string[];
  decisions: Array<{
    decision: string;
    rationale: string;
    alternatives: string[];
  }>;
}

export interface DevOutput {
  role: "dev";
  files_modified: string[];
  tests_added: string[];
  summary: string;
  issues_encountered: string[];
}

export interface QaOutput {
  role: "qa";
  score: number;
  findings: Array<{
    severity: "critical" | "important" | "minor" | "suggestion";
    description: string;
    suggestion: string;
    file?: string;
  }>;
  summary: string;
  tests_missing: string[];
}

export interface SmOutput {
  role: "sm";
  summary: string;
  blockers: string[];
  next_steps: string[];
  follow_ups: string[];
}

export interface PlannerOutput {
  role: "planner";
  feasibility: "high" | "medium" | "low";
  analysis: string;
  risks: Array<{
    severity: "high" | "medium" | "low";
    description: string;
  }>;
  subtasks: Array<{
    title: string;
    description: string;
    priority: number;
    acceptance_criteria: string;
    dependencies?: string[];
    files?: string[];
  }>;
  priorities: string[];
}

export interface ExplorerOutput {
  role: "explorer";
  etat_des_lieux: string;
  options: Array<{
    label: string;
    description: string;
    pros: string[];
    cons: string[];
  }>;
  recommandations: Array<{
    action: string;
    effort: "trivial" | "small" | "medium" | "large";
    impact: "low" | "medium" | "high";
    files: string[];
  }>;
  effort_estimate: {
    total: string;
    breakdown: string[];
  };
  references: string[];
}

/**
 * Structured output for the exploration phase in the workflow pipeline.
 * Richer than ExplorerOutput: includes domain, findings with sources,
 * alternatives with effort, risks with mitigation, confidence score.
 * Used when explorer runs as part of orchestrate() exploration phase.
 */
export interface ExplorationPhaseOutput {
  role: "explorer";
  domain: string;
  findings: Array<{
    title: string;
    description: string;
    sources: string[];
    relevance: "high" | "medium" | "low";
  }>;
  alternatives: Array<{
    label: string;
    description: string;
    pros: string[];
    cons: string[];
    effort: "trivial" | "small" | "medium" | "large";
  }>;
  recommendation: string;
  risks: Array<{
    severity: "high" | "medium" | "low";
    description: string;
    mitigation: string;
  }>;
  effort_estimate: string;
  confidence: number;
  open_questions: string[];
}

// ── Proto-Spec & Adversarial Schemas (P1/P2/E1/P3) ──────────

/** P1: Proto-spec generated by spec-lite agent before orchestration */
export interface ProtoSpec {
  objective: string;
  v_criteria: Array<{
    id: string;
    description: string;
    level: "unit" | "integration" | "E2E";
  }>;
  impacted_files: string[];
  generated_at: string;
  agent_model: string;
  duration_ms: number;
}

/** P2: Adversarial challenge result from Devil's Advocate */
export interface AdversarialResult {
  findings: Array<{
    id: string;
    severity: "BLOQUANT" | "MAJEUR" | "MINEUR";
    title: string;
    description: string;
    source: string;
  }>;
  stats: {
    bloquants: number;
    majeurs: number;
    mineurs: number;
  };
  /** PASS = challenge passed, PAUSE = bloquant found, SKIPPED = agent failed (F-DA-3) */
  verdict: "PASS" | "PAUSE" | "SKIPPED";
  duration_ms: number;
}

/** E1: Impact analysis result combining zero-LLM graph + optional agent */
export interface ImpactAnalysisResult {
  risk_level: "LOW" | "MEDIUM" | "HIGH";
  modules_impacted_direct: number;
  modules_impacted_transitive: number;
  breaking_changes: string[];
  attention_points: string[];
  /** true if analysis was zero-LLM only (< 3 files), false if agent was spawned */
  graph_only: boolean;
  duration_ms: number;
}

/** Union of all structured agent outputs */
export type StructuredAgentOutput =
  | AnalystOutput
  | PmOutput
  | ArchitectOutput
  | DevOutput
  | QaOutput
  | SmOutput
  | PlannerOutput
  | ExplorerOutput
  | ExplorationPhaseOutput;

// ── AgentMessage: wrapper around structured output ───────────

export interface AgentMessage {
  agentId: AgentRole;
  agentName: string;
  success: boolean;
  structured: StructuredAgentOutput | null;
  rawOutput: string;
  durationMs: number;
  error?: string | undefined;
}

// ── JSON Schema Descriptions (for injection into prompts) ────

const SCHEMA_DESCRIPTIONS: Record<AgentRole | "exploration", string> = {
  analyst: `{
  "role": "analyst",
  "analysis": "resume de l'analyse (2-3 paragraphes)",
  "risks": [{"severity": "high|medium|low", "description": "..."}],
  "recommendations": ["action 1", "action 2"],
  "dependencies": ["module ou systeme dont la tache depend"],
  "feasibility": "high|medium|low"
}`,
  pm: `{
  "role": "pm",
  "subtasks": [{
    "title": "titre court imperatif",
    "description": "contexte technique 1-2 phrases",
    "priority": 1,
    "acceptance_criteria": "Given/When/Then",
    "dependencies": ["autre sous-tache"]
  }],
  "priorities": ["priorite strategique 1"],
  "risks": ["risque identifie 1"]
}`,
  architect: `{
  "role": "architect",
  "design": "description de l'architecture proposee",
  "components": [{
    "name": "nom du composant",
    "responsibility": "sa responsabilite",
    "interactions": ["composant avec lequel il interagit"]
  }],
  "files_impacted": ["src/fichier.ts"],
  "patterns": ["pattern a suivre"],
  "technical_risks": ["risque technique"],
  "decisions": [{
    "decision": "choix fait",
    "rationale": "pourquoi",
    "alternatives": ["option rejetee"]
  }]
}`,
  dev: `{
  "role": "dev",
  "files_modified": ["src/fichier.ts"],
  "tests_added": ["tests/fichier.test.ts"],
  "summary": "resume de ce qui a ete fait",
  "issues_encountered": ["probleme rencontre et comment resolu"]
}`,
  qa: `{
  "role": "qa",
  "score": 85,
  "findings": [{
    "severity": "critical|important|minor|suggestion",
    "description": "probleme identifie",
    "suggestion": "correction proposee",
    "file": "src/fichier.ts"
  }],
  "summary": "resume de la review",
  "tests_missing": ["test manquant"]
}`,
  sm: `{
  "role": "sm",
  "summary": "synthese globale",
  "blockers": ["blocage actuel"],
  "next_steps": ["prochaine etape"],
  "follow_ups": ["point de suivi"]
}`,
  explorer: `{
  "role": "explorer",
  "etat_des_lieux": "description factuelle de l'etat actuel (2-3 paragraphes)",
  "options": [{"label": "Option A", "description": "...", "pros": ["avantage"], "cons": ["inconvenient"]}],
  "recommandations": [{"action": "action concrete", "effort": "trivial|small|medium|large", "impact": "low|medium|high", "files": ["src/fichier.ts"]}],
  "effort_estimate": {"total": "estimation globale", "breakdown": ["detail 1", "detail 2"]},
  "references": ["src/module.ts:42", "docs/adr/001.md"]
}`,
  exploration: `{
  "role": "explorer",
  "domain": "domaine technique explore (ex: authentification, base de donnees, API)",
  "findings": [{"title": "decouverte", "description": "details", "sources": ["src/module.ts:42"], "relevance": "high|medium|low"}],
  "alternatives": [{"label": "Option A", "description": "...", "pros": ["avantage"], "cons": ["inconvenient"], "effort": "trivial|small|medium|large"}],
  "recommendation": "recommandation finale en 1-2 phrases",
  "risks": [{"severity": "high|medium|low", "description": "risque", "mitigation": "comment le mitiger"}],
  "effort_estimate": "estimation globale (ex: 4-6h)",
  "confidence": 0.8,
  "open_questions": ["question non resolue"]
}`,
  planner: `{
  "role": "planner",
  "feasibility": "high|medium|low",
  "analysis": "resume de l'analyse de faisabilite (1-2 paragraphes)",
  "risks": [{"severity": "high|medium|low", "description": "risque identifie"}],
  "subtasks": [{
    "title": "titre court imperatif",
    "description": "contexte technique 1-2 phrases",
    "priority": 1,
    "acceptance_criteria": "Given/When/Then",
    "dependencies": ["autre sous-tache"],
    "files": ["src/fichier.ts"]
  }],
  "priorities": ["priorite strategique 1"]
}`,
};

/**
 * Get the JSON schema description for an agent role.
 * Used to inject into agent prompts so they produce structured output.
 */
export function getSchemaForRole(role: AgentRole): string {
  return SCHEMA_DESCRIPTIONS[role] || "";
}

// ── JSON Schema for --json-schema flag (S28-T4) ─────────────

/** Standard JSON Schemas for Claude CLI --json-schema flag */
const JSON_SCHEMAS: Record<string, object> = {
  analyst: {
    type: "object",
    properties: {
      role: { type: "string", const: "analyst" },
      analysis: { type: "string" },
      risks: {
        type: "array",
        items: {
          type: "object",
          properties: {
            severity: { type: "string", enum: ["high", "medium", "low"] },
            description: { type: "string" },
          },
          required: ["severity", "description"],
        },
      },
      recommendations: { type: "array", items: { type: "string" } },
      dependencies: { type: "array", items: { type: "string" } },
      feasibility: { type: "string", enum: ["high", "medium", "low"] },
    },
    required: ["role", "analysis", "risks", "recommendations"],
  },
  pm: {
    type: "object",
    properties: {
      role: { type: "string", const: "pm" },
      subtasks: {
        type: "array",
        items: {
          type: "object",
          properties: {
            title: { type: "string" },
            description: { type: "string" },
            priority: { type: "number" },
            acceptance_criteria: { type: "string" },
            dependencies: { type: "array", items: { type: "string" } },
          },
          required: ["title", "description", "priority"],
        },
      },
      priorities: { type: "array", items: { type: "string" } },
      risks: { type: "array", items: { type: "string" } },
    },
    required: ["role", "subtasks", "priorities"],
  },
  architect: {
    type: "object",
    properties: {
      role: { type: "string", const: "architect" },
      design: { type: "string" },
      components: {
        type: "array",
        items: {
          type: "object",
          properties: {
            name: { type: "string" },
            responsibility: { type: "string" },
            interactions: { type: "array", items: { type: "string" } },
          },
          required: ["name", "responsibility"],
        },
      },
      files_impacted: { type: "array", items: { type: "string" } },
      patterns: { type: "array", items: { type: "string" } },
      technical_risks: { type: "array", items: { type: "string" } },
      decisions: {
        type: "array",
        items: {
          type: "object",
          properties: {
            decision: { type: "string" },
            rationale: { type: "string" },
            alternatives: { type: "array", items: { type: "string" } },
          },
          required: ["decision", "rationale"],
        },
      },
    },
    required: ["role", "design", "files_impacted"],
  },
  dev: {
    type: "object",
    properties: {
      role: { type: "string", const: "dev" },
      files_modified: { type: "array", items: { type: "string" } },
      tests_added: { type: "array", items: { type: "string" } },
      summary: { type: "string" },
      issues_encountered: { type: "array", items: { type: "string" } },
    },
    required: ["role", "files_modified", "summary"],
  },
  qa: {
    type: "object",
    properties: {
      role: { type: "string", const: "qa" },
      score: { type: "number", minimum: 0, maximum: 100 },
      findings: {
        type: "array",
        items: {
          type: "object",
          properties: {
            severity: { type: "string", enum: ["critical", "important", "minor", "suggestion"] },
            description: { type: "string" },
            suggestion: { type: "string" },
            file: { type: "string" },
          },
          required: ["severity", "description", "suggestion"],
        },
      },
      summary: { type: "string" },
      tests_missing: { type: "array", items: { type: "string" } },
    },
    required: ["role", "score", "findings", "summary"],
  },
  sm: {
    type: "object",
    properties: {
      role: { type: "string", const: "sm" },
      summary: { type: "string" },
      blockers: { type: "array", items: { type: "string" } },
      next_steps: { type: "array", items: { type: "string" } },
      follow_ups: { type: "array", items: { type: "string" } },
    },
    required: ["role", "summary", "next_steps"],
  },
  planner: {
    type: "object",
    properties: {
      role: { type: "string", const: "planner" },
      feasibility: { type: "string", enum: ["high", "medium", "low"] },
      analysis: { type: "string" },
      risks: {
        type: "array",
        items: {
          type: "object",
          properties: {
            severity: { type: "string", enum: ["high", "medium", "low"] },
            description: { type: "string" },
          },
          required: ["severity", "description"],
        },
      },
      subtasks: {
        type: "array",
        items: {
          type: "object",
          properties: {
            title: { type: "string" },
            description: { type: "string" },
            priority: { type: "number" },
            acceptance_criteria: { type: "string" },
            dependencies: { type: "array", items: { type: "string" } },
            files: { type: "array", items: { type: "string" } },
          },
          required: ["title", "description", "priority"],
        },
      },
      priorities: { type: "array", items: { type: "string" } },
    },
    required: ["role", "feasibility", "analysis", "subtasks", "priorities"],
  },
  explorer: {
    type: "object",
    properties: {
      role: { type: "string", const: "explorer" },
      etat_des_lieux: { type: "string" },
      options: {
        type: "array",
        items: {
          type: "object",
          properties: {
            label: { type: "string" },
            description: { type: "string" },
            pros: { type: "array", items: { type: "string" } },
            cons: { type: "array", items: { type: "string" } },
          },
          required: ["label", "description"],
        },
      },
      recommandations: {
        type: "array",
        items: {
          type: "object",
          properties: {
            action: { type: "string" },
            effort: { type: "string", enum: ["trivial", "small", "medium", "large"] },
            impact: { type: "string", enum: ["low", "medium", "high"] },
            files: { type: "array", items: { type: "string" } },
          },
          required: ["action", "effort", "impact"],
        },
      },
      effort_estimate: {
        type: "object",
        properties: {
          total: { type: "string" },
          breakdown: { type: "array", items: { type: "string" } },
        },
        required: ["total"],
      },
      references: { type: "array", items: { type: "string" } },
    },
    required: ["role", "etat_des_lieux", "options", "recommandations"],
  },
  exploration: {
    type: "object",
    properties: {
      role: { type: "string", const: "explorer" },
      domain: { type: "string" },
      findings: {
        type: "array",
        items: {
          type: "object",
          properties: {
            title: { type: "string" },
            description: { type: "string" },
            sources: { type: "array", items: { type: "string" } },
            relevance: { type: "string", enum: ["high", "medium", "low"] },
          },
          required: ["title", "description"],
        },
      },
      alternatives: {
        type: "array",
        items: {
          type: "object",
          properties: {
            label: { type: "string" },
            description: { type: "string" },
            pros: { type: "array", items: { type: "string" } },
            cons: { type: "array", items: { type: "string" } },
            effort: { type: "string", enum: ["trivial", "small", "medium", "large"] },
          },
          required: ["label", "description"],
        },
      },
      recommendation: { type: "string" },
      risks: {
        type: "array",
        items: {
          type: "object",
          properties: {
            severity: { type: "string", enum: ["high", "medium", "low"] },
            description: { type: "string" },
            mitigation: { type: "string" },
          },
          required: ["severity", "description"],
        },
      },
      effort_estimate: { type: "string" },
      confidence: { type: "number", minimum: 0, maximum: 1 },
      open_questions: { type: "array", items: { type: "string" } },
    },
    required: ["role", "domain", "findings", "alternatives", "recommendation", "confidence"],
  },
  gate_evaluation: {
    type: "object",
    properties: {
      pass: { type: "boolean" },
      score: { type: "number", minimum: 0, maximum: 100 },
      issues: {
        type: "array",
        items: {
          type: "object",
          properties: {
            severity: { type: "string", enum: ["critical", "major", "minor"] },
            description: { type: "string" },
            suggestion: { type: "string" },
          },
          required: ["severity", "description"],
        },
      },
      gate_name: { type: "string" },
    },
    required: ["pass", "score", "issues", "gate_name"],
  },
  drift_report: {
    type: "object",
    properties: {
      coverage_score: { type: "number", minimum: 0, maximum: 100 },
      drift_items: {
        type: "array",
        items: {
          type: "object",
          properties: {
            fr_id: { type: "string" },
            status: { type: "string", enum: ["implemented", "missing", "partial", "divergent"] },
            details: { type: "string" },
          },
          required: ["fr_id", "status", "details"],
        },
      },
      overall_verdict: { type: "string", enum: ["pass", "fail", "warning"] },
    },
    required: ["coverage_score", "drift_items", "overall_verdict"],
  },
};

/**
 * Get the JSON Schema for a role, suitable for --json-schema flag.
 * S28: Returns a standard JSON Schema object for Claude CLI structured output.
 */
export function getJsonSchemaForRole(role: string): object | null {
  return JSON_SCHEMAS[role] || null;
}

/**
 * Build the structured output instruction block for an agent prompt.
 * Tells the agent to wrap its output in a JSON block.
 */
export function buildStructuredOutputInstructions(role: AgentRole): string {
  const schema = getSchemaForRole(role);
  if (!schema) return "";

  return [
    "",
    "FORMAT DE SORTIE OBLIGATOIRE:",
    "Tu DOIS produire ta reponse au format JSON structure.",
    "Entoure ton JSON avec les marqueurs <<<JSON>>> et <<<END>>>.",
    "Tu peux ecrire du texte libre avant et apres les marqueurs, mais le JSON est obligatoire.",
    "",
    "Schema attendu:",
    schema,
    "",
    "Exemple:",
    "<<<JSON>>>",
    schema,
    "<<<END>>>",
  ].join("\n");
}

// ── Parsing ──────────────────────────────────────────────────

/**
 * Extract structured JSON from agent raw output.
 * S28: First tries direct JSON parse (for --output-format json output).
 * Then looks for <<<JSON>>> ... <<<END>>> markers.
 * Falls back to finding any JSON object in the output.
 */
export function parseAgentOutput(
  rawOutput: string,
  role: AgentRole
): StructuredAgentOutput | null {
  // S28: Try direct JSON parse first (output from --output-format json)
  try {
    const direct = JSON.parse(rawOutput);
    if (validateAgentOutput(direct, role)) {
      return { ...direct, role } as StructuredAgentOutput;
    }
  } catch {
    // Not direct JSON, fall through to marker-based parsing
  }

  // Try marked JSON (<<<JSON>>> markers — legacy fallback)
  const markerMatch = rawOutput.match(
    /<<<JSON>>>\s*([\s\S]*?)\s*<<<END>>>/
  );
  if (markerMatch) {
    try {
      const parsed = JSON.parse(markerMatch[1]!.trim());
      if (validateAgentOutput(parsed, role)) {
        return { ...parsed, role } as StructuredAgentOutput;
      }
    } catch {
      // Fall through to fallback
    }
  }

  // Fallback: find the largest JSON object in the output
  const jsonMatches = findJsonObjects(rawOutput);
  for (const jsonStr of jsonMatches) {
    try {
      const parsed = JSON.parse(jsonStr);
      if (validateAgentOutput(parsed, role)) {
        return { ...parsed, role } as StructuredAgentOutput;
      }
    } catch {
      continue;
    }
  }

  return null;
}

/**
 * Find JSON object strings in text, sorted by length (largest first).
 */
function findJsonObjects(text: string): string[] {
  const results: string[] = [];
  let depth = 0;
  let start = -1;

  for (let i = 0; i < text.length; i++) {
    if (text[i] === "{") {
      if (depth === 0) start = i;
      depth++;
    } else if (text[i] === "}") {
      depth--;
      if (depth === 0 && start >= 0) {
        results.push(text.substring(start, i + 1));
        start = -1;
      }
    }
  }

  // Sort by length descending (largest JSON objects first)
  return results.sort((a, b) => b.length - a.length);
}

/**
 * Validate that a parsed object matches the expected schema for a role.
 * Checks for required fields — lenient validation (missing optional fields are OK).
 */
export function validateAgentOutput(
  obj: unknown,
  role: AgentRole
): boolean {
  if (!obj || typeof obj !== "object") return false;
  const o = obj as Record<string, unknown>;

  switch (role) {
    case "analyst":
      return (
        typeof o.analysis === "string" &&
        Array.isArray(o.risks) &&
        Array.isArray(o.recommendations)
      );
    case "pm":
      return (
        Array.isArray(o.subtasks) &&
        Array.isArray(o.priorities)
      );
    case "architect":
      return (
        typeof o.design === "string" &&
        Array.isArray(o.files_impacted)
      );
    case "dev":
      return (
        Array.isArray(o.files_modified) &&
        typeof o.summary === "string"
      );
    case "qa":
      return (
        typeof o.score === "number" &&
        Array.isArray(o.findings) &&
        typeof o.summary === "string"
      );
    case "sm":
      return (
        typeof o.summary === "string" &&
        Array.isArray(o.next_steps)
      );
    case "explorer":
      return (
        typeof o.etat_des_lieux === "string" &&
        Array.isArray(o.options) &&
        Array.isArray(o.recommandations)
      );
    case "planner":
      return (
        typeof o.feasibility === "string" &&
        typeof o.analysis === "string" &&
        Array.isArray(o.subtasks) &&
        Array.isArray(o.priorities)
      );
    default:
      return false;
  }
}

// ── Context Builder for Downstream Agents ────────────────────

/**
 * Build structured context from previous agent messages.
 * Instead of dumping raw text, extracts relevant fields per role.
 * S38: Optionally includes inter-agent messages.
 */
export function buildStructuredChainContext(
  messages: AgentMessage[],
  interAgentContext?: string
): string {
  if (messages.length === 0 && !interAgentContext) return "";

  const parts: string[] = ["CONTEXTE STRUCTURE DES AGENTS PRECEDENTS:"];

  for (const msg of messages) {
    if (!msg.success) continue;

    parts.push("");
    parts.push(`--- ${msg.agentName} (${msg.agentId}) ---`);

    if (msg.structured) {
      parts.push(formatStructuredOutput(msg.structured));
    } else {
      // Fallback to raw output (truncated)
      const truncated = msg.rawOutput.substring(0, 2000);
      parts.push(truncated);
      if (msg.rawOutput.length > 2000) parts.push("...(tronque)");
    }
  }

  // S38: Include inter-agent messages context
  if (interAgentContext) {
    parts.push("");
    parts.push(interAgentContext);
  }

  parts.push("");
  parts.push("Utilise ces outputs comme base. Ne repete pas ce qui a deja ete fait.");

  return parts.join("\n");
}

/**
 * Format a structured output for inclusion in downstream context.
 * Extracts the most relevant fields per role.
 */
export function formatStructuredOutput(output: StructuredAgentOutput): string {
  switch (output.role) {
    case "analyst":
      return [
        `Analyse: ${output.analysis}`,
        `Faisabilite: ${output.feasibility}`,
        output.risks.length > 0
          ? `Risques: ${output.risks.map((r) => `[${r.severity}] ${r.description}`).join("; ")}`
          : "",
        output.recommendations.length > 0
          ? `Recommandations: ${output.recommendations.join("; ")}`
          : "",
        output.dependencies.length > 0
          ? `Dependances: ${output.dependencies.join(", ")}`
          : "",
      ]
        .filter(Boolean)
        .join("\n");

    case "pm":
      return [
        `Sous-taches (${output.subtasks.length}):`,
        ...output.subtasks.map(
          (st, i) =>
            `  ${i + 1}. [P${st.priority}] ${st.title}: ${st.description}`
        ),
        output.risks.length > 0 ? `Risques: ${output.risks.join("; ")}` : "",
      ]
        .filter(Boolean)
        .join("\n");

    case "architect":
      return [
        `Design: ${output.design}`,
        output.components.length > 0
          ? `Composants: ${output.components.map((c) => `${c.name} (${c.responsibility})`).join(", ")}`
          : "",
        output.files_impacted.length > 0
          ? `Fichiers: ${output.files_impacted.join(", ")}`
          : "",
        output.decisions.length > 0
          ? `Decisions: ${output.decisions.map((d) => `${d.decision} (${d.rationale})`).join("; ")}`
          : "",
        output.technical_risks.length > 0
          ? `Risques techniques: ${output.technical_risks.join("; ")}`
          : "",
      ]
        .filter(Boolean)
        .join("\n");

    case "dev":
      return [
        `Resume: ${output.summary}`,
        output.files_modified.length > 0
          ? `Fichiers modifies: ${output.files_modified.join(", ")}`
          : "",
        output.tests_added.length > 0
          ? `Tests ajoutes: ${output.tests_added.join(", ")}`
          : "",
        output.issues_encountered.length > 0
          ? `Problemes: ${output.issues_encountered.join("; ")}`
          : "",
      ]
        .filter(Boolean)
        .join("\n");

    case "qa":
      return [
        `Score: ${output.score}/100`,
        `Resume: ${output.summary}`,
        output.findings.length > 0
          ? `Findings (${output.findings.length}): ${output.findings.map((f) => `[${f.severity}] ${f.description}`).join("; ")}`
          : "",
        output.tests_missing.length > 0
          ? `Tests manquants: ${output.tests_missing.join("; ")}`
          : "",
      ]
        .filter(Boolean)
        .join("\n");

    case "sm":
      return [
        `Synthese: ${output.summary}`,
        output.blockers.length > 0
          ? `Blocages: ${output.blockers.join("; ")}`
          : "",
        output.next_steps.length > 0
          ? `Prochaines etapes: ${output.next_steps.join("; ")}`
          : "",
      ]
        .filter(Boolean)
        .join("\n");

    case "planner":
      return [
        `Faisabilite: ${output.feasibility}`,
        `Analyse: ${output.analysis}`,
        output.risks.length > 0
          ? `Risques: ${output.risks.map((r) => `[${r.severity}] ${r.description}`).join("; ")}`
          : "",
        `Sous-taches (${output.subtasks.length}):`,
        ...output.subtasks.map(
          (st, i) =>
            `  ${i + 1}. [P${st.priority}] ${st.title}: ${st.description}`
        ),
      ]
        .filter(Boolean)
        .join("\n");

    case "explorer":
      if ("etat_des_lieux" in output) {
        const explorerOut = output as ExplorerOutput;
        return [
          `Etat des lieux: ${explorerOut.etat_des_lieux}`,
          explorerOut.options.length > 0
            ? `Options: ${explorerOut.options.map((o: { label: string; description: string }) => `${o.label} — ${o.description}`).join("; ")}`
            : "",
          explorerOut.recommandations.length > 0
            ? `Recommandations: ${explorerOut.recommandations.map((r: { effort: string; impact: string; action: string }) => `[${r.effort}/${r.impact}] ${r.action}`).join("; ")}`
            : "",
          explorerOut.effort_estimate
            ? `Effort: ${explorerOut.effort_estimate.total}`
            : "",
          explorerOut.references.length > 0
            ? `References: ${explorerOut.references.join(", ")}`
            : "",
        ]
          .filter(Boolean)
          .join("\n");
      }
      return formatExplorationPhaseOutput(output as ExplorationPhaseOutput);

    default:
      return JSON.stringify(output, null, 2);
  }
}

// ── Exploration Phase Output Parsing ─────────────────────────

/**
 * Validate that an object is a valid ExplorationPhaseOutput.
 * Checks required fields: domain, findings, alternatives, recommendation, confidence.
 */
export function validateExplorationPhaseOutput(obj: unknown): obj is ExplorationPhaseOutput {
  if (!obj || typeof obj !== "object") return false;
  const o = obj as Record<string, unknown>;
  return (
    typeof o.domain === "string" &&
    Array.isArray(o.findings) &&
    Array.isArray(o.alternatives) &&
    typeof o.recommendation === "string" &&
    typeof o.confidence === "number" &&
    o.confidence >= 0 &&
    o.confidence <= 1
  );
}

/**
 * Parse exploration phase output from raw agent output.
 * Tries JSON parse, then <<<JSON>>> markers, then fallback.
 * Returns null if parsing fails (caller should use raw output as fallback).
 */
export function parseExplorationPhaseOutput(rawOutput: string): ExplorationPhaseOutput | null {
  // Try direct JSON parse
  try {
    const parsed = JSON.parse(rawOutput);
    if (validateExplorationPhaseOutput(parsed)) {
      return { ...parsed, role: "explorer" } as ExplorationPhaseOutput;
    }
  } catch {
    // Not direct JSON
  }

  // Try <<<JSON>>> markers
  const markerMatch = rawOutput.match(/<<<JSON>>>\s*([\s\S]*?)\s*<<<END>>>/);
  if (markerMatch) {
    try {
      const parsed = JSON.parse(markerMatch[1]!.trim());
      if (validateExplorationPhaseOutput(parsed)) {
        return { ...parsed, role: "explorer" } as ExplorationPhaseOutput;
      }
    } catch {
      // Fall through
    }
  }

  // Fallback: find largest JSON object
  const jsonMatch = rawOutput.match(/\{[\s\S]*\}/);
  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch[0]);
      if (validateExplorationPhaseOutput(parsed)) {
        return { ...parsed, role: "explorer" } as ExplorationPhaseOutput;
      }
    } catch {
      // Fall through
    }
  }

  return null;
}

/**
 * Format ExplorationPhaseOutput for agent context injection.
 * Used in the "RAPPORT EXPLORATION" section of agent prompts.
 */
export function formatExplorationPhaseOutput(output: ExplorationPhaseOutput): string {
  const parts: string[] = [
    `Domaine: ${output.domain}`,
    `Confiance: ${Math.round(output.confidence * 100)}%`,
    `Recommandation: ${output.recommendation}`,
  ];

  if (output.findings.length > 0) {
    parts.push(`Decouvertes (${output.findings.length}):`);
    for (const f of output.findings) {
      const sources = f.sources?.length ? ` [${f.sources.join(", ")}]` : "";
      parts.push(`  [${f.relevance || "medium"}] ${f.title}: ${f.description}${sources}`);
    }
  }

  if (output.alternatives.length > 0) {
    parts.push(`Alternatives (${output.alternatives.length}):`);
    for (const a of output.alternatives) {
      parts.push(`  ${a.label} (${a.effort || "medium"}): ${a.description}`);
      if (a.pros?.length) parts.push(`    +: ${a.pros.join(", ")}`);
      if (a.cons?.length) parts.push(`    -: ${a.cons.join(", ")}`);
    }
  }

  if (output.risks?.length) {
    parts.push(`Risques: ${output.risks.map((r) => `[${r.severity}] ${r.description} -> ${r.mitigation || "?"}`).join("; ")}`);
  }

  if (output.effort_estimate) {
    parts.push(`Effort estime: ${output.effort_estimate}`);
  }

  if (output.open_questions?.length) {
    parts.push(`Questions ouvertes: ${output.open_questions.join("; ")}`);
  }

  return parts.join("\n");
}
